### ISSUE TITLE
Карточки для kwork поменять цвета

### ISSUE THREAD

**Issue by TheFoxKD** [SK-dev-mobile/sk-dev.site#1]
- android
- ios
- bots
- figma UI
- logos
- сайты (ruby on rails/django)

ВСЕ ЛЕЖИТ ЗДЕСЬ https://drive.google.com/drive/folders/1Iakc8xDQuviyK8GobygFXSbT-p8DLOn3?usp=sharing

![Image](https://user-images.githubusercontent.com/49817414/258644295-53c4be1d-6407-4c7d-88be-5abb87f801c4.png)
![Image](https://user-images.githubusercontent.com/49817414/258644296-acf98d94-7800-4917-97d0-0c5d602b1f6b.png)
![Image](https://user-images.githubusercontent.com/49817414/258644297-cc0bb24f-563a-43b2-85da-3f4193a3c8d5.png)
![Image](https://user-images.githubusercontent.com/49817414/258644298-f0352553-c75b-4c70-a361-cb6a1b30012b.png)
![Image](https://user-images.githubusercontent.com/49817414/258644299-7b588610-a64f-469f-b3f1-ace7fea7cf28.png)
![Image](https://user-images.githubusercontent.com/49817414/258644300-52ca2a88-d98a-4e23-aa98-3801a8936485.png)

**Comment by stakancheck** [comment]
На репе теперь assets/Images/Kwork cards
