### ISSUE TITLE
Купить память для мак мини

### ISSUE THREAD

**Issue by TheFoxKD** [SK-dev-mobile/sk-dev.site#4]
Приедет 12-14 августа

**Comment by TheFoxKD** [comment]
@stakancheck, приложи, пожалуйста, название или/и ссылку на модель внешнего SSD.

**Comment by stakancheck** [comment]
[Внешний SSD External Netac 512Gb ZX20 /NT01ZX20-512G-32BL/ (USB3.2 Gen2 x2 Type C, up to 2000/1800MBs, 71.5x43.5x8mm, Plastic) Black](https://www.ozon.ru/product/783838098/)
